---
- hosts: all
  become: true
  gather_facts: false
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Wait for SSH to come up
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300
      vars:
        ansible_user: ec2-user

- hosts: all
  become: true
  vars:
    ansible_user: ec2-user
  tasks:
  - name: Install Docker
    yum:
      name: docker
      state: latest

  - name: Start Docker Service
    service:
      name: docker
      state: started
      enabled: true

  - name: Add user
    command: usermod -a -G docker ec2-user

  - name: Install docker-compose
    command: pip3 install docker-compose

  - name: Create a new directory
    file:
      path: /home/ec2-user/hello-2048
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0775
  - name: Clone the GitHub repository
      command: wget https://raw.githubusercontent.com/vozsiberiana/hello-2048/main/docker-compose.yml

  - name: Docker-compose pull
      command: docker-compose pull

  - name: Docker-compose up
      command: docker-compose up -d

